name: Deploy icm-mos.ru

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: ./.github/actions/deploy@v1
        with:
          deploy_key: ${{secrets.DEPLOY_ENC_KEY}}
      - run: echo "icm-mos.ru was deployed at ${{ steps.deploy.outputs.time }}"
