name: Deploy icm-mos.ru

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: deploy
        uses: ./.github/actions/deploy@v1
        env:
          DEPLOY_ENC_KEY: ${{ secrets.DEPLOY_ENC_KEY }}
      - run: echo "icm-mos.ru was deployed at ${{ steps.deploy.outputs.time }}"
